[RAP-46] Add /domains endpoint to reseller API specs
unstoppabledomains/website-api-docs-v2 pull request #9
Opened 2022-10-12 20:32 UTC by Hrnt125

Add description for 'getMultiple' endpoint of Reseller API.
TODO: possibly need to fix 401 response for /domains/{domainName}.

2022-10-13 13:47 UTC, fruwe requested changes

2022-10-13 13:47 UTC, fruwe commented on openapi.yaml
> +    ResellerNotFound:
Let's use `PartnerNotFound` instead

2022-10-13 13:47 UTC, fruwe commented on openapi.yaml
> +            $ref: '#/components/schemas/DomainAvailabilityResponse'
```suggestion
            $ref: '#/components/schemas/Availability'
```

2022-10-13 13:47 UTC, fruwe commented on openapi.yaml
> +          $ref: '#/components/responses/DomainsBadRequest'
I think we can use `#/components/responses/BadRequest` should be good enough.

2022-10-13 14:07 UTC, Hrnt125 commented on openapi.yaml
> +            $ref: '#/components/schemas/DomainAvailabilityResponse'
{ "domains": [
   {
     # same as return value of /domains/{domainName} 
   }
] }

Availability is just 1 out of 2 parts we return in response.

2022-10-13 14:09 UTC, Hrnt125 commented on openapi.yaml
> +    ResellerNotFound:
PartnerNotFound describe not what actually is returned, I mentioned this when sent you screenshot

2022-10-13 14:13 UTC, Hrnt125 commented on openapi.yaml
>              $ref: '#/components/schemas/GeneralError'
I did not change this part, bit why for general 'BadRequest' we should return specific 'GeneralResellerNotFound'?

2022-10-13 18:08 UTC, fruwe requested changes

2022-10-13 18:08 UTC, fruwe commented on openapi.yaml
> +          example: 'some field'
NOTE: The API currently returns here `domainName`, but it should be `search`. Will need to get fixed in the future

2022-10-14 14:04 UTC, Hrnt125 commented on openapi.yaml
> +    ResellerNotFound:
--- Fixed ---

2022-10-14 14:05 UTC, Hrnt125 commented on openapi.yaml
> +          $ref: '#/components/responses/DomainsBadRequest'
--- Fixed ---

2022-10-14 14:06 UTC, Hrnt125 commented on openapi.yaml
> +      tags:
--- Fixed ---

2022-10-17 05:59 UTC, fruwe requested changes

2022-10-17 05:59 UTC, fruwe commented on openapi.yaml
> +    DomainInvalidNameError:
This seems to be no longer in use, let's remove this :)

2022-10-17 12:48 UTC, Hrnt125 commented on openapi.yaml
> +    DomainInvalidNameError:
I left it on purpose, like after MVP use it back, but np, I will remove an after add it if we need.

2022-10-18 01:26 UTC, Hrnt125 commented on openapi.yaml
> +    DomainInvalidNameError:
--- Fixed ---

2022-10-18 15:27 UTC, fruwe approved these changes
LGTM

2022-10-18 15:28 UTC, merged